# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: mailman3-fedmsg-plugin.spec

# add or remove files that should be synced
files_to_sync:
    - mailman3-fedmsg-plugin.spec
    - .packit.yaml

jobs:
- job: copr_build
  trigger: pull_request
  targets:
    - fedora-rawhide
    - fedora-40
    - fedora-39

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: mailman3-fedmsg-plugin
# downstream (Fedora) RPM package name
downstream_package_name: mailman3-fedmsg-plugin
