# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
  # License headers
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.1
    hooks:
      - id: reuse
